### ISSUE TITLE
Undo edits to Main levels

### ISSUE THREAD

**Issue by TeahersAreStupid1234** [FireMario211/Prism-Menu#1]
Hi, so i edited a main level on accident and now you cant collect the secret coins on it anymore. What can I do to deal with this?
I suggest an undo edits option to undo this

**Comment by FireMario211** [comment]
I could send you a .geode file to fix it, but it does mention in the Level Edit Hack that it is **NOT RECOMMENDED / UNSTABLE**
Which led me to disable it temporarily on v1.0.1

You can send me your Discord so I can help you resolve the issue and talk further, or I could send a .geode file directly here to try helping you fix it.

**Comment by TeahersAreStupid1234** [comment]
my dc is n0r1zz
