### ISSUE TITLE
Show hitboxes

### ISSUE THREAD

**Issue by Breelandthecat** [FireMario211/Prism-Menu#10]
This is much better and much more stable than my old mod menu (TobyAdd GDH), But could you please add show hitboxes and stuff? Otherwise i like this :)
Maybe fix speedhack audio too. Idk if its a setting off by default or not :)

**Comment by FireMario211** [comment]
Hitboxes already exist in settings
![image](https://github.com/FireMario211/Prism-Menu/assets/17692105/af73e67f-6be2-496a-8027-1627f9e02f3d)

Though I do plan on adding Hitbox trails and hitbox on death.

**Comment by Breelandthecat** [comment]
I Know, "Show Hitboxes" in the settings is practice mode.
![20240124165138_1](https://github.com/FireMario211/Prism-Menu/assets/136176622/1607b99d-c0fe-42ca-808f-474d23039191)
