### ISSUE TITLE
[Bug]: вылет бота

### ISSUE THREAD

**Issue by feach0999** [FireMario211/Prism-Menu#101]
### Platform

Android

### Version

1.6.4

### Describe the bug

вылетает игра после запуска макроса

### Expected Behavior

не должно вылетать

### How to reproduce

1.выбрать макрос
2.выбрать "произвести"
3.зайти в уровень
4.вылетает

### Mods Installed

только Prism Menu

### Crash Logs

[Crash 2024-06-06 12.14.29.dmp](https://github.com/user-attachments/files/15605282/Crash.2024-06-06.12.14.29.dmp)

**Comment by FireMario211** [comment]
https://github.com/FireMario211/Prism-Menu/blob/b6f221b8791df6c1139fe58cf03e3b549a55d75b/src/Hacks/Quartz.cpp#L510 🤔 

Я исправлю эту проблему
