### ISSUE TITLE
[Bug]: getting error and cant find a fix

### ISSUE THREAD

**Issue by Cheeser69420** [FireMario211/Prism-Menu#107]
### Platform

Android

### Version

v1.6.4

### Describe the bug

Trying to install it on Geode and it keeps giving me some error, cant find any fix for it
![Screenshot_20240617_115536_Geode](https://github.com/FireMario211/Prism-Menu/assets/173045403/19c166dc-768f-45e0-9fce-0929cd5ad865)

### Expected Behavior

Prob not giving me an error i cant find a fix for..

### How to reproduce

Any time i install it with the geode menu thing it just doesnt work

### Mods Installed

Had daily shop and pickup across sessions but it doesnt work even with those disabled

### Crash Logs

Didnt

### Additional Context

There isnt any, it just doesnt work
I put the error in the describe area and dont have anything else

**Comment by Cheeser69420** [comment]
Where can i even find that?
Also im a mobile player if that part wasnt clear (dont take it the wrong way, just wanted to say that)
I did find a 2.0.0 beta thingy but it has .so files and idk how the fuck to use them

**Comment by FireMario211** [comment]
You can find the option to turn on nightly in the settings of the Geode app
