### ISSUE TITLE
[Bug]: Crash when play a level

### ISSUE THREAD

**Issue by JrIIIGd** [FireMario211/Prism-Menu#113]
### Platform

Android

### Version

v1.8.0

### Describe the bug

If I join a level, I always got crash. Even a very leaf level I can't play.

### Expected Behavior

If I join a level I crash intermently

### How to reproduce

Nope

### Mods Installed

Only have prism menu mod

### Crash Logs

[Crash 2024-06-27 15.52.44.dmp](https://github.com/user-attachments/files/16011007/Crash.2024-06-27.15.52.44.dmp)

### Additional Context

Nope

**Comment by FireMario211** [comment]
Are you sure this is related to Prism? As in did you disable every mod but Prism and try playing a level? Because I don't see Prism in the stacktrace.

**Comment by JrIIIGd** [comment]
Yes I did

Vào 23:54, T.5, 27 Th6, 2024 Fire ***@***.***> đã viết:

**Comment by FireMario211** [comment]
I just realized that this bug report happens to Android32 users. If you're an android32 user, downgrade to v1.7.4 until this issue is fixed in a future update

https://github.com/FireMario211/Prism-Menu/releases/download/v1.7.4/firee.prism.geode

**Comment by JrIIIGd** [comment]
Ok

Vào 09:48, CN, 7 Th7, 2024 Fire ***@***.***> đã viết:
