### ISSUE TITLE
[Bug]: Prism menu doesn't open on mobile

### ISSUE THREAD

**Issue by FreakyVfo** [FireMario211/Prism-Menu#115]
### Platform

Android

### Version

v1.6.4

### Describe the bug

When i try to open the menu it doesn't open and when it does i can't activate anything

### How to reproduce

It just doesn't open

### Mods Installed

I only have prism menu

**Comment by FireMario211** [comment]
cant reproduce as I don't work on Prism Menu for 2.204 anymore
