### ISSUE TITLE
[Bug]: Crashes when editor is opened (without instant complete)

### ISSUE THREAD

**Issue by PlacidityIsEpic** [FireMario211/Prism-Menu#119]
### Platform

Mac OS

### Version

v1.8.1

### Describe the bug

When I enter the editor, the game crashes and there's no crash log pop up.

### How to reproduce

It just happened, like whenever i went into the editor then the game just crashed. It happens every time no matter what for me.

### Mods Installed

Node IDs, Prism Menu, GDShare, GMD API, Texture Loader

**Comment by FireMario211** [comment]
> It just happened, like whenever i went into the editor then the game **just crashed.** It happens every time no matter what for me.

# Crash logs
*No response*

**Comment by FireMario211** [comment]
Issue should be fixed in the recent **V1.8.2** update. Reopen this issue if the problem still persists.
