### ISSUE TITLE
[Bug]: Prism Menu is not opening 

### ISSUE THREAD

**Issue by hashedvoid** [FireMario211/Prism-Menu#131]
### Platform

Android 64

### Version

v1.8.2

### Describe the bug

I'm just make showcase, want to save, but Prism Menu is not opening.

### Expected Behavior

it should open.

### How to reproduce

Geometry Dash > Any level > Showcase this > Try to open prism menu.

### Mods Installed

Backups, Clicks sound, Custom keybinds, DevTools, Editor level id api, GMD Api, Globed, Grandpa demon, Jukebox, Newgrounds explorer, Node IDs, Trashcan

**Comment by FireMario211** [comment]
Are you able to showcase a video of this issue?

**Comment by hashedvoid** [comment]
This bug appears randomly.

**Comment by FireMario211** [comment]
Can't reproduce, but I'll assume the issue has been fixed. Reopen this issue if it still occurs.
