### ISSUE TITLE
red tint in high gamma setting

### ISSUE THREAD

**Issue by JerichoGesolgani** [FireMario211/Prism-Menu#134]
please remove the red tint, you can only see the red tint in the high gamma setting but you cant see it in low gamma setting go try it for your self and try disable and renable the mod you can see the difference in high gamma setting

**Comment by FireMario211** [comment]
what red tint are you talking about? Do you mean noclip flash

**Comment by JerichoGesolgani** [comment]
> what red tint are you talking about? Do you mean noclip flash

okay if you are confused i will explain carefully: the reason why i play the game in high gamma setting cuz it make darker part more easier but there one thing i just notice something. wherever the bg is black there bit red and i was like "oh maybe i have noclip flash on" but however its was off and i still see the a tiny red tint inside of the level which kinda distracting. but it could  be a noclip flash bug as i already disable it but i still see a tiny bit of red tint (only visible in high gamma setting not normal gamma setting) if you want try to test for your self like i said before, try go to display setting > advanced display settings > display adapter properties for display > color management (click on color management) > advanced > then "Calibrate display" > click next > then setting gamma setting to highest. after this try create a level with black bg and ground and enter the level you will notice the red tint if not then try to turn off and on the mod again and again. you will notice the difference. clear?

**Comment by FireMario211** [comment]
Turns out you are correct in that. After I increased the gamma setting to high, I do notice there is a bit of red, and I know exactly why that's the case.
I will fix that the next update.

**Comment by FireMario211** [comment]
> > Turns out you are correct in that. After I increased the gamma setting to high, I do notice there is a bit of red, and I know exactly why that's the case. It's because apparently, even if noclip flash is off, the "tint" is still there, despite it not supposed to be showing. I will fix that the next update.
> 
> thank man for reading carefully atleast you know now. also why there is not update since like month?

I've been busy mainly, and also I've been fixing other things for the next update (trying to fix the bot). The next update already has the fix implemented
