### ISSUE TITLE
Saving Issue

### ISSUE THREAD

**Issue by Breelandthecat** [FireMario211/Prism-Menu#14]
I Found a bug in Prism menu. Every time i restart the game, All settings get reset. Meaning that the prism button appears again. When i was in version 1.41 or whatever it was, It worked correctly, So in a recent update, It just erases settings on restart.

**Comment by FireMario211** [comment]
How are you exiting the game? And I need more information such as what platform you are on, what version, etc.

**Comment by Breelandthecat** [comment]
I Use windows 11, The way i exit the game is by doing the in-game exit button in the main menu.
![20240124180301_1](https://github.com/FireMario211/Prism-Menu/assets/136176622/7bb84910-87e5-43a1-bfa5-a7dd9f4b08b0)
For the version, I'm not exactly sure, But i think its around the newest version. I Know its definitely after 2.201, But im not sure. Probably 2.205 or 2.204

**Comment by FireMario211** [comment]
I meant for Prism Menu, not GD.
Like this for example.
![image](https://github.com/FireMario211/Prism-Menu/assets/17692105/94115362-79d9-4fc2-906c-e49503bd3ca4)

**Comment by Breelandthecat** [comment]
Oh, Its v1.2.1

**Comment by FireMario211** [comment]
Are you able to join the Discord linked here: https://discord.gg/pnD8cnwdhZ
So I can further help you with the issue and potentially fix it for others?

**Comment by Breelandthecat** [comment]
idk

**Comment by FireMario211** [comment]
Issue should be fixed in the recent v1.2.2 update.

**Comment by Breelandthecat** [comment]
ok ill test it

**Comment by Breelandthecat** [comment]
Fixed ty
