### ISSUE TITLE
Add Uncomplete Level

### ISSUE THREAD

**Issue by Lsteel7** [FireMario211/Prism-Menu#152]
It would be cool

**Comment by FireMario211** [comment]
it already exists
![image](https://github.com/user-attachments/assets/1b269046-5ae0-4a78-9671-dba0f3d8fa45)

**Comment by Lsteel7** [comment]
> it already exists ![image](https://private-user-images.githubusercontent.com/17692105/367616439-1b269046-5ae0-4a78-9671-dba0f3d8fa45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTA1NjgsIm5iZiI6MTcyNjQ5MDI2OCwicGF0aCI6Ii8xNzY5MjEwNS8zNjc2MTY0MzktMWIyNjkwNDYtNWFlMC00YTc4LTk2NzEtZGJhMGYzZDhmYTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEyMzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMDAyZWM5YzYxNDljNTQ3NzJiZmYzMzc4Njk3YWIzMjU2ZTRkNjBjOGQ2Y2RmYWJmOGY0YmQ2YjExM2UxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I5S0yvbShCfnZp3dSGg-SBI07co1OaMa8pR6Cm-fhpc)

oh, I didn't see, thank you very much
