### ISSUE TITLE
[Bug]: Settings do not persist on restart

### ISSUE THREAD

**Issue by DizzyJune** [FireMario211/Prism-Menu#16]
### Platform

Android

### Version

v1.2.1

### Describe the bug

I am on android, using Geode 2.0.0-beta.9, on GD version 2.2.05, and Prism v1.2.1. Whenever restarting, my settings do not save, and instead reset to the default. I've even tried editing the saved.json stored in /storage/emulated/0/Android/media/com.geode.launcher/save/geode/mods/firee.PrismMenu.

### Expected Behavior

Settings save when restarting.

### How to reproduce

Load up the game with android Geode, change settings, restart, and boom, settings aren't saved.

### Additional Context

N/A

**Comment by Breelandthecat** [comment]
I'm experiencing the same issue on windows too.

**Comment by FireMario211** [comment]
I haven't experienced it myself, however I will attempt to fix it for the next update.

**Comment by FireMario211** [comment]
Issue should be fixed in the recent v1.2.2 update.
