### ISSUE TITLE
Where is the gdr path?

### ISSUE THREAD

**Issue by MatkopiesXD** [FireMario211/Prism-Menu#166]
### Platform

Windows

### Version

v1.9.2

### Describe the bug

its a pretty good macro and i can also import but where is the directory to the .gdr files? i want to import them to another device

### How to reproduce

tell me the path or any other way for me to acess the .gdr files

### Mods Installed

i have the node ids thing and thats pretty much it

**Comment by FireMario211** [comment]
this isnt a bug, more of a question
Anyways, copy pasted from the Prism Menu discord:
# How do I view where my macros are located?
For Windows: `%localappdata%\GeometryDash\geode\mods\firee.prism\macros`
For Mac: `/Users/<name>/Library/Application Support/Geometry Dash/geode/mods/firee.prism/macros`
For Android: `/Android/media/com.geode.launcher/save/geode/mods/firee.prism/macros`

**Comment by MatkopiesXD** [comment]
Sorry I dont use steam there is no geometry dash in the %appdata% im using simple folder with the games content and the geometry dash game itself

**Comment by FireMario211** [comment]
> Sorry I dont use steam there is no geometry dash in the %appdata% im using simple folder with the games content and the geometry dash game itself

It shouldn't matter if you use Steam version or pirated version. Unless the name of the executable is something else than GeometryDash.exe, it'll remain in the local appdata directory.
Also **%localappdata%**, not **%appdata%**

**Comment by MatkopiesXD** [comment]
Thank you for helping me
