### ISSUE TITLE
[Bug]: Timewarp triggers reset speedhack

### ISSUE THREAD

**Issue by Bigmancozmo** [FireMario211/Prism-Menu#17]
### Platform

Windows

### Version

V1.2.2

### Describe the bug

When using speedhack, game speed can be reset by timewarp triggers.

### Expected Behavior

Speedhack isn't affected by timewarp triggers

### How to reproduce

1. Set speedhack to something other than 1x
2. Make a level with timewarp trigger set to below 1x then after that, add one set to 1x
3. Play the level. Speedhack is reset to 1x

**Comment by MegaSa1nt** [comment]
Rob probably uses same thing as speedhack :trollface:

**Comment by FireMario211** [comment]
> Rob probably uses same thing as speedhack :trollface:

thats very true
anyways I'll try fixing that for next update.

**Comment by FireMario211** [comment]
this should be fixed on the next update v1.3.0
