### ISSUE TITLE
"No (C)", "Edit any Level", etc. not in mod menu

### ISSUE THREAD

**Issue by TeahersAreStupid1234** [FireMario211/Prism-Menu#2]
**Describe the bug** (A clear and concise description of what the bug is)
I remember seeing some editor-related options such as "No (C)", "Edit any Level", etc. but they're not in the menu anymore. However, if you have enabled any of these before, it still functions in-game but cannot be disabled.
**How to reproduce** (In steps)
Idk, it just disappeared after I updated to 1.0.2.
**Expected behavior** (What you think is supposed to happen)
The options in the mod menu being visible
**Screenshots** (Optional)
![image](https://github.com/FireMario211/Prism-Menu/assets/59105483/7a9afca8-8bd3-4bb4-bb34-6c8b55deb320)

**Version** (Mod version)
1.0.2
**Platform** (Windows, Android, etc.)
Windows
**Additional context** (Any other information)

**Comment by FireMario211** [comment]
Will be fixed for next update
