### ISSUE TITLE
id[Bug]: 

### ISSUE THREAD

**Issue by lilbabyadrian** [FireMario211/Prism-Menu#20]
### Platform

Windows

### Version

idk

### Describe the bug

how do i get the modn menu in my game

### Expected Behavior

idk

### How to reproduce

idk

### Additional Context

idk

**Comment by FireMario211** [comment]
Not a bug, you get the mod by following these steps (Make sure you are on either Windows or Android):
1. Download Geode
2. Go to the Geode button
3. Go to the Download Tab
4. Scroll down until you find **Prism Menu**
5. Download it
6. You now have the mod.
