### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by TeahersAreStupid1234** [FireMario211/Prism-Menu#25]
![image](https://github.com/FireMario211/Prism-Menu/assets/59105483/6de81867-038e-47a8-b257-21e00e74dd8f)
No offense, but I absolutely hate this new UI. Give an option to change it back, please.
Oh, and, I want to work on Traditional Chinese and Simplified Chinese Translations :)

**Comment by TeahersAreStupid1234** [comment]
wait sorry image is wrong
![image](https://github.com/FireMario211/Prism-Menu/assets/59105483/3ff8b3e7-6c7e-4183-ba69-667331a588ad)

**Comment by MegaSa1nt** [comment]
Agree

**Comment by FireMario211** [comment]
This is added back in the recent update **v1.4.0**
Simply go to Settings, scroll all the way down, and change the Menu Style.
