### ISSUE TITLE
[Bug]: Show Layout

### ISSUE THREAD

**Issue by MalikHw** [FireMario211/Prism-Menu#26]
### Platform

Android

### Version

V1.3.2

### Describe the bug

Show layout on but looks like off

### How to reproduce

Just fix

**Comment by FireMario211** [comment]
I should mention this but Layout Mode currently doesn't work on Android and Mac as the mod can't be compiled with it on.

**Comment by FireMario211** [comment]
This is added in the recent update **v1.4.0**
