### ISSUE TITLE
Copy Hack on Password Protected Levels

### ISSUE THREAD

**Issue by Aktimoose** [FireMario211/Prism-Menu#3]
**Describe the bug**
Copy Hack does not work on password protected levels, it creates a new button under the copy button that is already there but it is inaccessible

**How to reproduce**
Enable Copy Hack
Attempt to copy any password protected level, such as [Biru](https://gdutils.com/47611766)

**Expected behavior**
The level can be copied without inputting a password

**Screenshots**
![20240120121358_1](https://github.com/FireMario211/Prism-Menu/assets/44620677/5bca05e9-2e70-49e1-b1bb-854523258027)
![image](https://github.com/FireMario211/Prism-Menu/assets/44620677/2c364451-a292-42b3-9eaf-8a1ddb696deb)

**Version**
v1.0.2

**Platform**
Windows

**Comment by FireMario211** [comment]
that shouldn't happen, I'll fix that

**Comment by FireMario211** [comment]
Said on Discord you couldn't replicate. I also used the same mods you stated and couldn't replicate.
Not sure what happened but I'll assume fixed.
