### ISSUE TITLE
[Bug]: Game crashes when i manually set the menu button's X/Y position.

### ISSUE THREAD

**Issue by AverageMaipuperson** [FireMario211/Prism-Menu#30]
### Platform

Android

### Version

v1.3.2

### Describe the bug

This bug happens when going into the menu's settings and going down to find "Button Position X" and "Button Position Y", with the slider it should work normally, but when i manually set the number typing it down on the number that's on the square left on the slider it doesn't change position and instead it crashes the game.
![Screenshot_20240205-232644~2](https://github.com/FireMario211/Prism-Menu/assets/152216368/ab95757a-3240-4690-bea8-b5ee5c470016)

### Expected Behavior

For expected behaviour, it should set the X or Y position of the button normally like doing it with the slider, just type in a number and it should be set to that position.

### How to reproduce

1. Go into the mod menu
2. Go into settings and scroll down until you find "Button Position (X/Y)"
3. Press on the box you find at the left of the slider and type any number on it
4. Game crashes.

**Comment by AverageMaipuperson** [comment]
I forgot to add additional context, but this crash only happens when you set the number to the original position your button had

**Comment by FireMario211** [comment]
This should be fixed in the recent **v1.5.0** update. Reopen the issue if you still are having it.
