### ISSUE TITLE
[Bug]: The text from the help boxes break at some circumstances.

### ISSUE THREAD

**Issue by AverageMaipuperson** [FireMario211/Prism-Menu#31]
### Platform

Android

### Version

v1.3.2

### Describe the bug

The text on the help boxes for some mods are positioned in a way that you can't read it because they are phasing with other texts, like in the image below.[
![Screenshot_20240206-191757](https://github.com/FireMario211/Prism-Menu/assets/152216368/21338ddb-89e5-410c-907f-94d6dda2432e)
](url)

### How to reproduce

uhh just go to the menu press on one of these help buttons left from the mods and just see that the text is broken

### Additional Context

This may happen because of device, graphics, or window space.

**Comment by FireMario211** [comment]
This is due to the screen.
Are you able to share the display resolution of your Android device?

**Comment by AverageMaipuperson** [comment]
> This is due to the screen. Are you able to share the display resolution of your Android device?

I can't get my resolution, but by comparing it, the closest is to 1600x1024

**Comment by FireMario211** [comment]
This was fixed in **V1.4.2**. Only reopen the issue if you have any questions or this issue is still occuring.
