### ISSUE TITLE
[Bug]: Menu doesn't open on MacOS

### ISSUE THREAD

**Issue by ronran1** [FireMario211/Prism-Menu#33]
### Platform

Mac OS

### Version

1.4.0

### Describe the bug

Neither tab nor clicking on the menu button in the Esc screen opens Prism. However, the practice mode hack is still working.

<img width="1693" alt="SCR-20240207-ogsr" src="https://github.com/FireMario211/Prism-Menu/assets/14254688/4ce9cb53-5a55-4535-ac70-598446fa67b4">

### Expected Behavior

Tab -> Prism Menu

### How to reproduce

Pressing tab or the icon for menu button.

### Additional Context

MacOS M1 Max chip. 1.3.2 worked fine.

**Comment by FireMario211** [comment]
Should be fixed in the recent **v1.4.1** update.
