### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Helloausername** [FireMario211/Prism-Menu#34]
### Platform

Android

### Version

latest version

### Describe the bug

geode crashing when entering  a number at gravity

### Expected Behavior

idk

### How to reproduce

I'm Romanian so I'm what it means so I type what I think it means: open prism menu go to player type in the box a number at gravity and it crashes

### Additional Context

bla bla bla

**Comment by FireMario211** [comment]
This should be fixed in the recent **v1.5.0** update. Reopen the issue if you still are having it.
