### ISSUE TITLE
[Bug]: the game freezes when Jumphack is enable in-game

### ISSUE THREAD

**Issue by Faisalkhan2266** [FireMario211/Prism-Menu#35]
### Platform

Android

### Version

1.4.1

### Describe the bug

This issue only happens when you're in the middle of the level. When you try to disable or enable Jump hack in the middle of platformer and classic level. The Game freezes in the middle of the level. You can't do anything besides exiting and re-entering the level to fix this. 

If this is solvable where you enable a high jump in the middle of the level then it will resolve this issue. 

### Expected Behavior

If this is solvable where you enable a high jump in the middle of the level then it will resolve this issue. 

### How to reproduce

- you play any level
- while in the middle of the level
- you pause the game and tap on the prism menu
- you enable High Jump
- you go back to the pause screen
- now no button works, it has all frozen

The only button you can tap is Backward in your phone which exits you out of the level. When you enter back to the level. The high Jump is enabled. Upon disabling it also makes your game freeze.

**Comment by AverageMaipuperson** [comment]
Did you accidentally set the speedhack to 0.00? or is that you accidentally activated force platformer mode in android?

**Comment by Faisalkhan2266** [comment]
No, even when I reset the settings. The issue still exists. It was never an issue on the previous version. I start noticing it in 1.4.1. 
1. The speed hack is set to normal which is 1.0
2. There is no Force mode enable on android.

**Comment by AverageMaipuperson** [comment]
> No, even when I reset the settings. The issue still exists. It was never an issue on the previous version. I start noticing it in 1.4.1.
> 
> 1. The speed hack is set to normal which is 1.0
> 2. There is no Force mode enable on android.

Force platformer mode got added in 1.4.0 btw

**Comment by FireMario211** [comment]
This was fixed in **V1.4.2**. Only reopen the issue if you have any questions or this issue is still occuring.
