### ISSUE TITLE
Add buttons to force platformer mode option (only to android)

### ISSUE THREAD

**Issue by AverageMaipuperson** [FireMario211/Prism-Menu#36]
Glad the new update added force platformer mode, but it doesn't have buttons to go directions, i recommend adding these in future updates.
![Screenshot_20240209-163835](https://github.com/FireMario211/Prism-Menu/assets/152216368/b4de4f1a-cd2a-4e41-9ca3-9ef882812b6a)

**Comment by FireMario211** [comment]
Will be added.
