### ISSUE TITLE
[Bug]: Cheat indicator mark disappears when a camera effect is played

### ISSUE THREAD

**Issue by Flyingturtle215** [FireMario211/Prism-Menu#38]
### Platform

Windows

### Version

v1.4.1

### Describe the bug

When a level with camera effects is played with cheat indicator enabled, the cheat indicator icon disappears from time to time based on what camera effects are played and the durations of the camera effects.

### Expected Behavior

Cheat indicator mark should stay on-screen and visible for the entirety of the level.

### How to reproduce

- Enable cheat indicator mod
- Play a level with camera effects (for example, Dash by RobTop)
- The cheat indicator mark will disappear periodically based on what camera effects are being played and for how long

**Comment by FireMario211** [comment]
Will be fixed for next update

**Comment by FireMario211** [comment]
This was fixed in **V1.4.2**. Only reopen the issue if you have any questions or this issue is still occuring.
