### ISSUE TITLE
[Bug]: Noclip accuracy doesn't work

### ISSUE THREAD

**Issue by EledgarioXd** [FireMario211/Prism-Menu#39]
### Platform

Windows

### Version

v1.4.1

### Describe the bug

The noclip accuracy does'nt work, it only shows the percentage at 100% but when you want to play a level with that, simply touching an obstacle dies but the noclip accuracy percentage does not decrease

### How to reproduce

Uploading Geometry Dash 2024-02-10 15-14-40.mp4…

**Comment by FireMario211** [comment]
As the info suggests, you have to enable **Anticheat Bypass** in order for Noclip Accuracy to work.
