### ISSUE TITLE
Kinda necessary tweaks :3

### ISSUE THREAD

**Issue by DXGOfficial** [FireMario211/Prism-Menu#4]
It's gonna be really cool, if Prism Menu's button will be normally worked with BetterMenu, and don't layered a daily/weekly buttons.
![Screenshot_20240120_214142_com geode launcher](https://github.com/FireMario211/Prism-Menu/assets/157183465/743c21ed-2bbf-46f3-bb1b-3d9fce7560fd)
P.S. Also, can you add more flexible and mobile-friendly speedhack slider, or just a Custom SH Speed from IAD's Mod Menu?

**Comment by DXGOfficial** [comment]
UPD: Ok, i'm just realized, that the button position is setting up in Misc, also, what in the hell, the Gravity Changer is not working on Mobile (i'm actually press checkbox, but it's not changing), and, why i'm can't click menu toggle button in the Main Menu (again, i have BetterMenu enabled, i'm don't checked with vanilla main menu)?

**Comment by FireMario211** [comment]
For Gravity Change, I cant do much about that because someone has to fix bindings for Geode on Android.

As for the button not working in the main menu, I'll fix that soon. It's not any mods fault.

**Comment by DXGOfficial** [comment]
Thanks, but i'm think, it will be cool to see automated position of toggle button with BetterMenu support, and for else everywhere your own position.
I'm think, this is not hard to code.
THX anyway.

**Comment by FireMario211** [comment]
I accidentally made it integrated for BetterMenu
(ignore the normal icon on the letf)
![image](https://github.com/FireMario211/Prism-Menu/assets/17692105/165a3ae0-a7f6-4cf1-8416-3bd06ca45d6d)
