### ISSUE TITLE
Feature Request: Kill player toggle

### ISSUE THREAD

**Issue by tulpenkiste** [FireMario211/Prism-Menu#40]
I think this could be nice addition, mainly for the "players destroyed" achievements (due to how tedious it is normally)

**Comment by FireMario211** [comment]
basically the "Suicide" hack from MHV5, could add that

**Comment by FireMario211** [comment]
You added that in the recent PR you made at https://github.com/FireMario211/Prism-Menu/pull/48
I'll close this as completed.
