### ISSUE TITLE
[Bug]: Jump hack bug

### ISSUE THREAD

**Issue by Breelandthecat** [FireMario211/Prism-Menu#42]
### Platform

Windows

### Version

v1.4.1

### Describe the bug

Enabling jump hack in a platformer level and moving causes you to jump. I Had to compress the video due to the original being too large.

https://github.com/FireMario211/Prism-Menu/assets/136176622/ce959679-ebcf-42ea-b23b-641d054da8bb

### Expected Behavior

I Think that it isnt supposed to do anything at all besides what it does in normal mode. It shouldnt register a jump hacked jump when moving left or right in platformer.

### How to reproduce

1: Go into a platformer level or into any level with force platformer on.
2: Enable jump hack.
3: Move left or right.

### Mods Installed

![image](https://github.com/FireMario211/Prism-Menu/assets/136176622/a1b6aaa3-c9d8-4012-940f-2109380e2a58)
those are all of my mods.

**Comment by FireMario211** [comment]
This was fixed in **V1.4.2**. Only reopen the issue if you have any questions or this issue is still occuring.

**Comment by Breelandthecat** [comment]
Ty fixed
