### ISSUE TITLE
i can translate prismmenu into romanian

### ISSUE THREAD

**Issue by Helloausername** [FireMario211/Prism-Menu#44]
im romanian so i can translate it if you want

**Comment by FireMario211** [comment]
I would recommend joining the server for further discussion on translations
https://discord.gg/pnD8cnwdhZ

**Comment by Helloausername** [comment]
> I would recommend joining the server for further discussion on translations https://discord.gg/pnD8cnwdhZ

i dont have discord

**Comment by FireMario211** [comment]
> i dont have discord

You may have to create a pull request then if you want to translate, and I'll look it over.
