### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Helloausername** [FireMario211/Prism-Menu#45]
### Platform

Android

### Version

latest

### Describe the bug

when entering a level then quitting the levl i cant open the menu

### Expected Behavior

idk

### How to reproduce

join a level quit it and click the button and it dosent work

### Mods Installed

backup, betteredit, clean startpos, click sounds, compact lists, gdshare,gmd api,likebaitexterminator,more settings button,node ids,run info and youtubers

### Additional Context

will comment to see if it still dosent work to open the menu without the mods

**Comment by Helloausername** [comment]
when i enter a level and leave it i can open the menu but when i close it i cant open it anymore only in the pause menu

**Comment by FireMario211** [comment]
@Helloausername Can you specify specifically what version you're on?

**Comment by Helloausername** [comment]
> @Helloausername Can you specify specifically what version you're on? Not latest.

1.4.2

**Comment by FireMario211** [comment]
Can't reproduce, but I'll assume the issue has been fixed. Reopen this issue if it still occurs.
