### ISSUE TITLE
[Bug]: Jump hack breaks when upside down

### ISSUE THREAD

**Issue by Breelandthecat** [FireMario211/Prism-Menu#49]
### Platform

Windows

### Version

v1.4.2

### Describe the bug

With jump hack enabled, While upside down, You can jump normally, If you jump midair, You fling up like a black orb as if you were upside down. But the flinging up is while your upside down and stuff, So jumping midair is kinda like hitting a black orb upside down.

### Expected Behavior

I Think its supposed to be the same as on normal gravity, But instead it flaps you down.

### How to reproduce

1: Go in a level and go into a upside down portal or a upside down pad or just go upside down in any way
2: Make sure you have jump hack.
3: Jump.
You might notice the cube jumps normally.
4: Jump midair
This is the part where it acts like you hit a black orb while upside down.

### Mods Installed

I'm on my laptop, So i do have a different selection of mods, But they shouldnt be too different
![image](https://github.com/FireMario211/Prism-Menu/assets/136176622/82f75065-dc8c-42f0-b8f9-b2eb61ea134e)

### Additional Context

Also i think its meant to play the normal jump animation when jumping midair or on the ground instead of spin backwards slowly and do a tiny jump. Kind of an extra, I Think bug report.

**Comment by FireMario211** [comment]
Oh I know exactly why it's like that. I never checked if the player is upside down. I can try fixing that though.

**Comment by Breelandthecat** [comment]
ok

**Comment by Breelandthecat** [comment]
https://github.com/FireMario211/Prism-Menu/assets/136176622/aff4912b-4a53-4ec5-8bf8-8994cb8e11ae

**Comment by FireMario211** [comment]
This has been fixed in the recent **v1.5.0** update.
