### ISSUE TITLE
Crashes when playing certain levels

### ISSUE THREAD

**Issue by walmartbag104** [FireMario211/Prism-Menu#5]
Prism apparently crashes my game when playing my own uploaded levels. It doesn't happen when playing any other levels from what i've seen (I use windows)
![image](https://github.com/FireMario211/Prism-Menu/assets/157221262/c033f699-2725-4cf5-ae2d-f805a43c15a8)

**Comment by FireMario211** [comment]
What hacks did you have enabled, and what version of Prism is this?

**Comment by walmartbag104** [comment]
i only have copy hack, hide attempts and hide playtest enabled and it's v1.0.2

**Comment by FireMario211** [comment]
I recently pushed a new version (v1.1.0) Did the new version fix this?

**Comment by Alyoshadash** [comment]
No, she still exists. Previously, there didn’t seem to be this error when version 1.0.1 was there, I updated to 1.1.0, it appeared, I disable the functions and it doesn’t work, rolling back the version doesn’t work either. I have this problem when I go to the page of my uploaded 2.1 levels (it doesn’t crash with my 2.2 levels)

**Comment by FireMario211** [comment]
What about in v1.1.1?

**Comment by Alyoshadash** [comment]
So far, everything is the same. (Only I was a little mistaken, most likely the levels that you made without this mod will crash, and those you made with the mod will not crash in (Maybe only the last level that you posted will not crash))

**Comment by Alyoshadash** [comment]
Everything in the new version of this mod no longer contains this bug.

**Comment by FireMario211** [comment]
That's great to hear. I apologize if you had this issue, but I'm glad you don't get it anymore 👍
