### ISSUE TITLE
[Bug]: The slopes are not working while on noclip mode

### ISSUE THREAD

**Issue by ThatOrang98** [FireMario211/Prism-Menu#50]
### Platform

Android

### Version

v1.4.2

### Describe the bug

The slopes are not working like if you slide on it it's not working
It's hard to explain 

### Expected Behavior

Nothing maybe

### How to reproduce

I don't know

### Mods Installed

I only have Prism Menu

### Crash Logs

No

### Additional Context

That's all

**Comment by FireMario211** [comment]
Do you have Noclip enabled but not Anticheat Bypass?

If not, that is why. Enable Anticheat Bypass if you want to use Noclip and want slopes to work.
