### ISSUE TITLE
[Bug]: Menu disappears on transition

### ISSUE THREAD

**Issue by scrahe** [FireMario211/Prism-Menu#51]
### Platform

Mac OS

### Version

v1.4.2

### Describe the bug

When clicking a button on any page that transitions to another page while opening the menu, the menu disappears once that transition is done.

### Expected Behavior

It should stay on the screen instead of disapearing.

### How to reproduce

Press tab and click on the create menu at the same time.

### Mods Installed

beat.click-sound.geode
blackholemx.nomoregames.geode
cvolton.betterinfo.geode
firee.PrismMenu.geode
geode.node-ids.geode
geode.texture-loader.geode
ninxout.crystal_client.geode (Disabled)
raydeeux.likebaitexterminator.geode
thesillydoggo.better_startpos_menu.geode

**Comment by FireMario211** [comment]
Unfortunately due to limitations with cocos, I can't really do that.
