### ISSUE TITLE
[Bug]: Along with many other mods, speedhack audio does not work

### ISSUE THREAD

**Issue by scrahe** [FireMario211/Prism-Menu#53]
### Platform

Mac OS

### Version

v1.4.2

### Describe the bug

Many of the mods don't actually work, such as speedhack audio

### Expected Behavior

The mods should work

### How to reproduce

Click on speedhack audio, and it doesn't work

### Mods Installed

beat.click-sound.geode
blackholemx.nomoregames.geode
cvolton.betterinfo.geode
firee.PrismMenu.geode
geode.node-ids.geode
geode.texture-loader.geode
ninxout.crystal_client.geode (Disabled)
raydeeux.likebaitexterminator.geode
thesillydoggo.better_startpos_menu.geode

**Comment by FireMario211** [comment]
Mostly due to me wanting to get it out for Mac OS, hence why some mods don't work.
I will fix speedhack audio and other hacks in a future update 👍
