### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by Breelandthecat** [FireMario211/Prism-Menu#54]
### Platform

Windows

### Version

v1.4.1 (updating to 1.4.2 rn)

### Describe the bug

I Opened gd and it instantly crashed and said it was related to firee.prism menu

### Expected Behavior

I Think it should just startup normally

### How to reproduce

You cant really reproduce it and its quite rare.

### Mods Installed

a "x" before the mod version and name means its enabled. If its not a "x" then its installed but disabled.

x | [v1.0.5] abb2k.backup
x | [v1.1.1] adyagd.godlikefaces
x | [v1.1.1] adyagd.ingamelistmod
x | [v1.1.1] alphalaneous.deathlink
x | [v1.0.1] alphalaneous.happy_textures
x | [v1.0.1] alphalaneous.hide
x | [v1.0.0] alphalaneous.playercolorselect
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.2] arkane.dl-team-icons
x | [v1.0.5] b1rtek.gddlintegration
x | [v1.4.4] beat.click-sound
x | [v1.0.5] bitz.customprofiles
x | [v1.0.1] blueblock6.cleanstartpos
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.1.3] capeling.demons_in_garage_2.2
  | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.1.4] cdc.more-hints
x | [v1.0.1] cj_link.fakemoderator
x | [v1.0.1] coderqc.gdswearfilter
x | [v1.0.2] colon.bumpscosity
  | [v2.0.1] colon.gd_in_2019
x | [v4.0.0] cvolton.betterinfo
x | [v1.0.5] dankmeme.globed2
  | [v1.0.2] dogotrigger.roulette
  | [v1.1.1] ekv.hidePauseMenuHack
x | [v1.0.0] ekv.save_on_level_page
  | [v1.2.2] elnexreal.copy_song_id
x | [v1.0.0] elnexreal.demonlistinfo
x | [v1.5.0] elohmrow.death_tracker
x | [v1.0.0] elsai.copyright_remover_for_main_levels
x | [v1.0.0] elsai.pause_menu_zoom
x | [v1.0.3] firee.GoldenBest
x | [v1.4.1] firee.PrismMenu
x | [v2.4.0] fleym.nongd
  | [v1.2.15] gdutilsdevs.gdutils
x | [v1.5.2] geode.custom-keybinds
  | [v1.5.0] geode.devtools
x | [v2.0.0-beta.19] geode.loader
x | [v1.4.0] geode.node-ids
  | [v1.5.0] geode.texture-loader
x | [v1.0.0] hiimjustin000.integrated_demonlist
x | [v6.2.1] hjfod.betteredit
x | [v1.0.4] hjfod.gdshare
x | [v1.0.1] hjfod.gmd-api
x | [v1.0.2] iristraa.spinoffsubtitles
x | [v1.0.1] itzkiba.elegant_rankings
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.0.0] izzy.practice_sync
x | [v1.0.0] jojo989.main_menu_bg_customizer
x | [v1.1.0] khronophobia.more_settings_button
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v1.0.0] mat.reference-image
x | [v1.0.2] mat.run-info
x | [v1.1.0] mat.scroll-zoom
  | [v2.5.0] maxnu.gd_mega_overlay
x | [v1.0.0-beta.2] minemaker0430.gddp_integration
  | [v1.0.4-beta.12] muhammadgames.bettermenu
x | [v1.0.3] n.level_pronouns
  | [v1.2.1] n.robtop-jumpscare
x | [v1.1.0] ninkaz.blending_glow
x | [v1.2.1] oatmealine.ids_integration
x | [v1.2.0] oatmealine.nlw_integration
  | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v1.1.0] polsk.level_quests
x | [v1.0.0] polsk.pause_settings
x | [v1.6.1] prevter.openhack
x | [v1.0.0] raydeeux.antilobotomy
x | [v1.0.0] raydeeux.likebaitexterminator
x | [v1.0.0] raydeeux.poofshowbutton
  | [v1.2.1] shineua.minecraft_splash
  | [v1.0.4] skyward.no_robtop_logo
x | [v2.3.0] techstudent10.discord_rich_presence
x | [v1.0.0] techstudent10.hide_locks
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.1.0] thesillydoggo.better_startpos_menu
  | [v1.1.3] TheSillyDoggo.Cheats
x | [v1.0.0] thesillydoggo.entersearch
  | [v2.1.0] TheSillyDoggo.GradientPages
  | [v1.1.1] TheSillyDoggo.StartposSwitcher
x | [v1.5.5] tpdea.betterpause-Better
x | [v1.8.0] undefined0.gdtweaks
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.0.2] weebify.coins_in_pause_menu
x | [v1.1.1] weebify.jumpscare
x | [v1.0.1] weebify.level_info_in_pause_menu
x | [v1.0.2] weebify.restartbtn
x | [v1.0.0] xanii.freaky_mode
x | [v1.0.2] xanii.youtubers
  | [v1.4.1] zilko.xdbot
x | [v0.1.2] zohnannor.dark_mode

### Crash Logs

2024-02-16T18:32:32-0600
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "firee.PrismMenu" mod. Please submit this crash report to its developers (Firee) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.19
Loader Commit: b78c6b1
Bindings Commit: b904f47
Installed mods: 93
Problems: 2

== Exception Information ==
Faulty Module: E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll
Faulty Mod: firee.PrismMenu
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 78CC1D07 (firee.PrismMenu.dll + 51d07)
Number Parameters: 2

== Stack Trace ==
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 51d07
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 5164d
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 50cd2
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 2c7ee
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 55730
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 5975e
 - 02EE1B0B
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 23995
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 29c5e
 - 02EE1B0B
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\undefined0.gdtweaks\undefined0.gdtweaks.dll + 8be1
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\undefined0.gdtweaks\undefined0.gdtweaks.dll + 162b
 - 02EE1B0B
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 276b0a
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 177b2
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 1805e
 - 175B382B
 - 02EE18C9
 - 02EE16EB
 - E:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 3f696 (geode::EventFilter<geode::IndexUpdateEvent>::getListener + 12198)
 - 02EE16EB
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 8f484 (cocos2d::CCActionInterval::step + 180)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 91564 (cocos2d::CCActionManager::update + 116)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 106e02 (cocos2d::CCScheduler::update + 82)
 - 02EE2D76
 - 02EE2B97
 - 02EE2B97
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 9e36
 - 02EE2B97
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - E:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 16c264 (crashlog::setupPlatformHandlerPost + 3956)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 00000000
EBX: 1c313cb0
ECX: ffffffd8
EDX: 00000003
EBP: 00cfeae8
ESP: 00cfeac8
EDI: 00000001
ESI: 1c5a4698
EIP: 78cc1d07

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v1.1.1] adyagd.godlikefaces
x | [v1.1.1] adyagd.ingamelistmod
x | [v1.1.1] alphalaneous.deathlink
x | [v1.0.1] alphalaneous.happy_textures
x | [v1.0.1] alphalaneous.hide
x | [v1.0.0] alphalaneous.playercolorselect
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.2] arkane.dl-team-icons
x | [v1.0.5] b1rtek.gddlintegration
x | [v1.4.4] beat.click-sound
x | [v1.0.5] bitz.customprofiles
x | [v1.0.1] blueblock6.cleanstartpos
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.1.3] capeling.demons_in_garage_2.2
  | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.1.4] cdc.more-hints
x | [v1.0.1] cj_link.fakemoderator
x | [v1.0.1] coderqc.gdswearfilter
x | [v1.0.2] colon.bumpscosity
  | [v2.0.1] colon.gd_in_2019
x | [v4.0.0] cvolton.betterinfo
x | [v1.0.5] dankmeme.globed2
  | [v1.0.2] dogotrigger.roulette
  | [v1.1.1] ekv.hidePauseMenuHack
x | [v1.0.0] ekv.save_on_level_page
  | [v1.2.2] elnexreal.copy_song_id
x | [v1.0.0] elnexreal.demonlistinfo
x | [v1.5.0] elohmrow.death_tracker
x | [v1.0.0] elsai.copyright_remover_for_main_levels
x | [v1.0.0] elsai.pause_menu_zoom
x | [v1.0.3] firee.GoldenBest
x | [v1.4.1] firee.PrismMenu
x | [v2.4.0] fleym.nongd
  | [v1.2.15] gdutilsdevs.gdutils
x | [v1.5.2] geode.custom-keybinds
  | [v1.5.0] geode.devtools
x | [v2.0.0-beta.19] geode.loader
x | [v1.4.0] geode.node-ids
  | [v1.5.0] geode.texture-loader
x | [v1.0.0] hiimjustin000.integrated_demonlist
x | [v6.2.1] hjfod.betteredit
x | [v1.0.4] hjfod.gdshare
x | [v1.0.1] hjfod.gmd-api
x | [v1.0.2] iristraa.spinoffsubtitles
x | [v1.0.1] itzkiba.elegant_rankings
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.0.0] izzy.practice_sync
x | [v1.0.0] jojo989.main_menu_bg_customizer
x | [v1.1.0] khronophobia.more_settings_button
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v1.0.0] mat.reference-image
x | [v1.0.2] mat.run-info
x | [v1.1.0] mat.scroll-zoom
  | [v2.5.0] maxnu.gd_mega_overlay
x | [v1.0.0-beta.2] minemaker0430.gddp_integration
  | [v1.0.4-beta.12] muhammadgames.bettermenu
x | [v1.0.3] n.level_pronouns
  | [v1.2.1] n.robtop-jumpscare
x | [v1.1.0] ninkaz.blending_glow
x | [v1.2.1] oatmealine.ids_integration
x | [v1.2.0] oatmealine.nlw_integration
  | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v1.1.0] polsk.level_quests
x | [v1.0.0] polsk.pause_settings
x | [v1.6.1] prevter.openhack
x | [v1.0.0] raydeeux.antilobotomy
x | [v1.0.0] raydeeux.likebaitexterminator
x | [v1.0.0] raydeeux.poofshowbutton
  | [v1.2.1] shineua.minecraft_splash
  | [v1.0.4] skyward.no_robtop_logo
x | [v2.3.0] techstudent10.discord_rich_presence
x | [v1.0.0] techstudent10.hide_locks
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.1.0] thesillydoggo.better_startpos_menu
  | [v1.1.3] TheSillyDoggo.Cheats
x | [v1.0.0] thesillydoggo.entersearch
  | [v2.1.0] TheSillyDoggo.GradientPages
  | [v1.1.1] TheSillyDoggo.StartposSwitcher
x | [v1.5.5] tpdea.betterpause-Better
x | [v1.8.0] undefined0.gdtweaks
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.0.2] weebify.coins_in_pause_menu
x | [v1.1.1] weebify.jumpscare
x | [v1.0.1] weebify.level_info_in_pause_menu
x | [v1.0.2] weebify.restartbtn
x | [v1.0.0] xanii.freaky_mode
x | [v1.0.2] xanii.youtubers
  | [v1.4.1] zilko.xdbot
x | [v0.1.2] zohnannor.dark_mode

**Comment by Breelandthecat** [comment]
updated

**Comment by FireMario211** [comment]
Does the recent update fix the issue @Breelandthecat ?
Or are you still experiencing it?

**Comment by Breelandthecat** [comment]
Sorry about the delay, I Kinda left geometry dash and i dont play it anymore and havent played it in a long time, So i probably wont report any bugs.
