### ISSUE TITLE
Custom Bindings

### ISSUE THREAD

**Issue by Breelandthecat** [FireMario211/Prism-Menu#55]
Could you please add a option for a custom key to open the GUI? Maybe a option to make a hack shortcut too. (Like right clicking a mod or hack and pressing a key then when you press the key you just pressed, it toggles that mod or hack. And it saves idk)

**Comment by FireMario211** [comment]
i need to add this

**Comment by FireMario211** [comment]
This has been implemented in the **V1.7.0** update.
