### ISSUE TITLE
[Bug]: Button shows after opening pause

### ISSUE THREAD

**Issue by Breelandthecat** [FireMario211/Prism-Menu#57]
### Platform

Windows

### Version

v1.4.2

### Describe the bug

Whenever opening the pause menu ingame, The prism menu button appears where it would with show button on, But when it appears, It stays there until you turn show button on then back off.

### Expected Behavior

I Think it should never show up unless show button is on

### How to reproduce

Go into a level.
Open pause.

### Mods Installed

![image](https://github.com/FireMario211/Prism-Menu/assets/136176622/33970189-b977-4f3c-b36a-1ff780341b93)

**Comment by glistermelon** [comment]
dunno why this issue wasn't seen first but [here you go](https://github.com/FireMario211/Prism-Menu/issues/67#issuecomment-1970237816)

**Comment by FireMario211** [comment]
This has been implemented in the **V1.8.0** update (https://github.com/FireMario211/Prism-Menu/commit/50e2ae835b43a1b48169d34f951fb057e2de6231)
