### ISSUE TITLE
[Bug]: It stopped working on Wine :(

### ISSUE THREAD

**Issue by Wionsito** [FireMario211/Prism-Menu#64]
### Platform

Windows

### Version

v1.4.0+

### Describe the bug

The game (running on a program based on Wine) crashes while it is loading, It has always worked in versions before 1.4.0

### Expected Behavior

The game should run without problems.

### How to reproduce

Open the game using Wine and Prism Menu 1.4.0+

### Mods Installed

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.1.2] b1rtek.gddlintegration
x | [v1.0.5] bitz.customprofiles
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.1.4] capeling.demons_in_garage_2.2
x | [v1.0.5] capeling.gamemode_picker
x | [v1.1.4] capeling.icon_profile_2.2
x | [v4.0.0] cvolton.betterinfo
x | [v1.2.2] dankmeme.globed2
x | [v1.0.0] elnexreal.auto_priority
x | [v1.0.0] elnexreal.demonlistinfo
x | [v1.5.1] elohmrow.death_tracker
x | [v1.3.0] elsai.a_daily_shop
x | [v1.0.2] elsai.brightness_mod
x | [v1.0.2] elsai.pause_menu_zoom
x | [v1.0.3] firee.GoldenBest
x | [v1.4.2] firee.PrismMenu
x | [v2.5.1] fleym.nongd
x | [v1.2.16] gdutilsdevs.gdutils
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.21] geode.loader
x | [v1.6.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v6.3.3] hjfod.betteredit
x | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
x | [v1.0.1] hjfod.quick-volume-controls
x | [v1.0.1] itzkiba.elegant_rankings
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v0.1.5] lexi.visiblecheckpoints
x | [v1.1.3] mat.circle-tool
x | [v1.0.1] mat.draw-divide
x | [v1.0.1] mat.max-window
x | [v1.0.2] mat.run-info
x | [v1.1.0] mat.scroll-zoom
x | [v1.0.3] n.level_pronouns
x | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v1.1.1] redlime.statchanges
x | [v1.1.1] shineua.geometrize2gd
x | [v1.0.2] slammy333.save_button
x | [v1.0.0] techstudent10.hide_locks
x | [v1.3.0] terma.ambienticons
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.6.9] thesillydoggo.entersearch
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.1.1] TheSillyDoggo.StartposSwitcher
x | [v1.6.2] tpdea.betterpause-Better
  | [v1.0.1] undefined0.autocheckpoint
x | [v1.9.0] undefined0.gdtweaks
x | [v1.0.0] uproxide.accupracatt
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.0.0] viper.gamemode_only
x | [v1.0.4] weebify.coins_in_pause_menu
x | [v1.0.3] weebify.level_info_in_pause_menu

### Crash Logs

Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.21
Loader Commit: 06afbb8
Bindings Commit: ff44163
Installed mods: 57
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00000000 (GeometryDash.exe + ffc00000)
Number Parameters: 2

== Stack Trace ==

== Register States ==
EAX: 62ae9878
EBX: 01b1ab98
ECX: 0012faf8
EDX: 7bb3fa26
EBP: 00000000
ESP: 0012fadc
EDI: 016e5420
ESI: 016e5420
EIP: 00000000

### Additional Context

This doesn't happen when using Prism Menu versions lower than 1.4.0 like 1.3.2.

I know that probably the mod working on Wine isn't a priority, but it would help me, I'm actually using macOS not Linux, but there's almost no mods on the mac version at least right now, that's why I'm using Wine (CrossOver).

**Comment by FireMario211** [comment]
It doesn't work with Wine for Mac OS because after v1.3.2, ImGui was added back.

If you would like, I can provide a build without ImGui so you can use Prism Menu without issues, you can ping me on the Discord Server and I can provide the .geode file.

**Comment by Wionsito** [comment]
> It doesn't work with Wine for Mac OS because after v1.3.2, ImGui was added back and Wine for Mac OS can't really handle it.

Ohh, I didn't know
> 
> If you would like, I can provide a build without ImGui so you can use Prism Menu without issues, you can ping me on the Discord Server and I can provide the .geode file.

Yes, tysm :)
