### ISSUE TITLE
[Bug]: Disabling "Show Button" doesn't hide button in pause menu

### ISSUE THREAD

**Issue by Bituvo** [FireMario211/Prism-Menu#67]
### Platform

Windows

### Version

v1.5.0-dev

### Describe the bug

When the "Show Button" option is disabled, the button still appears in the pause menu.

### Expected Behavior

It shouldn't appear.

### How to reproduce

1. Disable the option.
2. Play a level.
3. Open the pause menu.
4. Observe the button is still there.

### Mods Installed

:(

**Comment by FireMario211** [comment]
The version shouldn't be dev, I guess github ignores that huh

I'll just say, this isn't a bug.

The reason why the button is still there is in case mobile users accidentally disable it, as there's no other way to enable it back. However for Windows users, I can make the exception to remove it from the pause menu as well.

**Comment by su226** [comment]
> The reason why the button is still there is in case mobile users accidentally disable it, as there's no other way to enable it back. However for Windows users, I can make the exception to remove it from the pause menu as well.

Maybe add something like "force show button" in mod settings like this?
![force show button](https://github.com/FireMario211/Prism-Menu/assets/17371317/0129e189-a62b-47cf-b5d6-cd407760ce6e)

**Comment by FireMario211** [comment]
true, okay ill do that!

**Comment by FireMario211** [comment]
> > The reason why the button is still there is in case mobile users accidentally disable it, as there's no other way to enable it back. However for Windows users, I can make the exception to remove it from the pause menu as well.
> 
> Maybe add something like "force show button" in mod settings like this? ![force show button](https://private-user-images.githubusercontent.com/17371317/339793490-0129e189-a62b-47cf-b5d6-cd407760ce6e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzIxNTYsIm5iZiI6MTcxOTQzMTg1NiwicGF0aCI6Ii8xNzM3MTMxNy8zMzk3OTM0OTAtMDEyOWUxODktYTYyYi00N2NmLWI1ZDYtY2Q0MDc3NjBjZTZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE5NTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ODA2YTAzZWU1OGFhMDlmNjM4ZmJkZGM3YjU2NjkzMGE1YTgwODk2YjhhYmYwNWM4MzFmNTRmYjgxM2Q2ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5LU2XV0LrK9bb-ceteknYfQwn9nZjTLXrcmHwRYUPY)

https://github.com/FireMario211/Prism-Menu/commit/50e2ae835b43a1b48169d34f951fb057e2de6231 added
