### ISSUE TITLE
Add the ability so the menu only appears in the editor pause menu

### ISSUE THREAD

**Issue by Epyx15** [FireMario211/Prism-Menu#68]
Basically in the editor the botton to show the menu blocks the undo/redo bottons and when I move the botton lower it blocks other thing so my suggestion would be so you can hide the botton on the editor but show it in the pause editor menu
![Screenshot_20240229_113820_Geode](https://github.com/FireMario211/Prism-Menu/assets/160792200/7ce72d6d-166c-4962-a1e7-1537e81e5278)

**Comment by FireMario211** [comment]
I forgot to mention but this was added in the recent **v1.5.1** update.
