### ISSUE TITLE
[Request]: Add Hitbox Trail so that i can create frame perfect levels.

### ISSUE THREAD

**Issue by Ayhouu** [FireMario211/Prism-Menu#70]
### Platform

Android

### Version

v1.5.0

### Describe the bug

.

### Expected Behavior

.

### How to reproduce

.

### Mods Installed

.

### Crash Logs

.

### Additional Context

.

**Comment by FireMario211** [comment]
Not a bug and already suggested

**Comment by Ayhouu** [comment]
> Not a bug and already suggested
 
are you adding it tho?
