### ISSUE TITLE
Add no Hitboxes

### ISSUE THREAD

**Issue by Ayhouu** [FireMario211/Prism-Menu#71]
A mod where there are no Hitboxes which means you cant touch anything, basically no clip but you cant stand on blocks.

**Comment by FireMario211** [comment]
https://github.com/FireMario211/Prism-Menu/blob/884d384219d47862a61b516f00211725cb5ec69f/resources/hacks/player.json#L19
It's already in, although it's not implemented for 2.2

**Comment by Ayhouu** [comment]
> https://github.com/FireMario211/Prism-Menu/blob/884d384219d47862a61b516f00211725cb5ec69f/resources/hacks/player.json#L19
> 
> 
> It's already in, although it's not implemented for 2.2

for Android
