### ISSUE TITLE
[Bug]: character filter and character limit won't work

### ISSUE THREAD

**Issue by TymTymXD** [FireMario211/Prism-Menu#74]
### Platform

Windows

### Version

1.5.0

### Describe the bug

character filter and character limit won't work

### Expected Behavior

they should work

### How to reproduce

install the mod

### Mods Installed

i have a lot of mods (i am too lazy to type them out)

**Comment by TymTymXD** [comment]
yeah platform is not window it's Linux btw

**Comment by FireMario211** [comment]
I disabled the functionality because people were complaining of crashes

> os is not windows it's Linux
OS doesn't matter in this context. Linux runs wine / proton to play GD, so it's assumed to be a Windows issue.

**Comment by TymTymXD** [comment]
oh ok
