### ISSUE TITLE
Crashes When Entering Shop

### ISSUE THREAD

**Issue by TheFouke** [FireMario211/Prism-Menu#8]
Game crashes when entering any shop (regular, scratch, community, mechanic, diamond) when mod is installed.

Crash Log:

2024-01-22T17:56:46-0600
Whoopsies! An unhandled exception has occured.

== Geode Information ==
Loader Version: v2.0.0-beta.6
Loader Commit: 8473e5d
Bindings Commit: d787873
Installed mods: 15
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 79B83570 (libcocos2d.dll + 63570 (cocos2d::CCArray::count + 0))
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 63570 (cocos2d::CCArray::count + 0)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + a6c4
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + a967
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\firee.PrismMenu\firee.PrismMenu.dll + 1a6ee
 - 00FD2397
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2f92e (geode::modifier::AsStaticFunction_willSwitchToScene<SceneSwitch,void (__thiscall SceneSwitch::*)(cocos2d::CCScene *)>::Impl<void (__thiscall SceneSwitch::*)(cocos2d::CCScene *)>::function + 14 | D:\a\geode\geode\build\codegenned\Geode\modify\AchievementNotifier.hpp:31)
 - 00FD2397
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 1048ff (cocos2d::CCDirector::willSwitchToScene + 31)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + aa1b3 (cocos2d::CCTransitionMoveInL::onEnter + 99)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + c1266 (gdMainHook + 406 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:58)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 00000000
EBX: 00000000
ECX: 00000000
EDX: 00000001
EBP: 00f8f804
ESP: 00f8f7ac
EDI: 00000000
ESI: 00000000
EIP: 79b83570

== Installed Mods ==
  | [v2.1.0] fleym.nongd
  | [v1.0.2] n.level_pronouns
x | [v2.0.0-beta.6] geode.loader
  | [v1.2.12] gdutilsdevs.gdutils
  | [v1.1.0] alphalaneous.projectedstars
  | [v1.0.1] bitz.customprofiles
x | [v1.1.3] firee.PrismMenu
  | [v1.0.1] capeling.goodbye_unnecessary_buttons
  | [v1.0.1] itzkiba.grandpa_demon
  | [v4.0.0-alpha.6] cvolton.betterinfo
  | [v1.1.3] geode.node-ids
  | [v1.4.0] geode.texture-loader
  | [v1.0.4] hjfod.gdshare
  | [v1.0.1] hjfod.gmd-api
  | [v1.0.4-beta.12] muhammadgames.bettermenu

**Comment by AuthentiCuber** [comment]
I have the same problem, and it doesn't happen with prism menu disabled

**Comment by FireMario211** [comment]
What version are you both on? The latest?
And what prism mods do you have enabled?

**Comment by FireMario211** [comment]
Fixed in the recent version.
