### ISSUE TITLE
[Bug]: Game Crash

### ISSUE THREAD

**Issue by GDCorona** [FireMario211/Prism-Menu#81]
### Platform

Windows

### Version

v1.5.1

### Describe the bug

Sometimes the game crash right after I opened. I have uploaded the crashlog folder pls see what's wrong with it

### How to reproduce

I dont understand 

### Mods Installed

I only installed Prism Menu

### Crash Logs

[2024-03-31_20-02-47.log](https://github.com/FireMario211/Prism-Menu/files/14815966/2024-03-31_20-02-47.log)

**Comment by FireMario211** [comment]
Seems like an issue with ImGui (as shown in the screenshot I gave)
![image](https://github.com/FireMario211/Prism-Menu/assets/17692105/b11e611a-f523-499a-aa34-0fdb035aba26)

You can download the non-imgui version, which should fix the issue:
https://prism.firee.dev/noimgui/latest/firee.PrismMenu.geode
