### ISSUE TITLE
[Bug]: tps bypass reset setting

### ISSUE THREAD

**Issue by VeensCal** [FireMario211/Prism-Menu#82]
### Platform

Android

### Version

1.6.0 beta

### Describe the bug

When I tried 360 tps and I quit the game it resets

### Expected Behavior

None

### How to reproduce

Open geode
Open prism menu
Change tps
Quit the game
Reset

### Mods Installed

Prism ,qol mod, and more

### Crash Logs

No crash log it's a bug

### Additional Context

No

**Comment by FireMario211** [comment]
it's not a bug, that's intended
it's mainly because I haven't implemented saving for patching yet, you can view in the README.md here for more information:

https://github.com/FireMario211/Prism-Menu/blob/main/resources/hacks/README.md
