### ISSUE TITLE
[Bug]: Turning on Practice Music unlocks all of the Paths

### ISSUE THREAD

**Issue by Bluezcreen** [FireMario211/Prism-Menu#84]
### Platform

Android

### Version

1.5.1

### Describe the bug

When I turn on Practice music, the paths on the Paths of Power menu unlocks, even if I hadn't unlocked them yet.

### Expected Behavior

The Paths shouldn't've unlocked.

### How to reproduce

Turn on Practice Music, and check the Paths menu. You'll see the paths that you hadn't unlocked yet get unlocked.

### Mods Installed

Prism Menu, BetterInfo, BetterEdit, XDbot

**Comment by FireMario211** [comment]
thats a very bad bug, will have to fix after I release update

**Comment by Bluezcreen** [comment]
when i updated prism again, apparently the bug is still there



also cool skin

**Comment by FireMario211** [comment]
> apparently when i updated prism again, the bug is still there
> 
> also cool skin

In the next update, I'll just disable Practice Music. I think I know why it does this, but I'm not sure how to exactly fix it. It's also not just paths, it also unlocks other things you aren't supposed to unlock.

**Comment by Rubiidev-18** [comment]
> Holy moly this is actually real
> 
> ![image](https://private-user-images.githubusercontent.com/68702247/324242692-539d865d-ef48-4cb5-853c-62ff821c987a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDU4NjcsIm5iZiI6MTcxNDIwNTU2NywicGF0aCI6Ii82ODcwMjI0Ny8zMjQyNDI2OTItNTM5ZDg2NWQtZWY0OC00Y2I1LTg1M2MtNjJmZjgyMWM5ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA4MTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZTdkM2E2MGMxYjJiOTc5N2FhNGFlZDFmMzM3YjI4ZmYxZTI1ZWQ2OGRjYzVjNjNlNjlhMDhmMTg5NmZhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ij-77dvRZgdT4aL7C9ziYInH-30i9HF7BwvD38vU3Ss)

off topic but can you get me the texture loader texture pack files for this tp + add the uhd texture android files for uhd support

**Comment by FireMario211** [comment]
Issue should be fixed in the recent **V1.6.4** update. Reopen this issue if the problem still persists.
