### ISSUE TITLE
[Bug]: Quick vid of how it crashs

### ISSUE THREAD

**Issue by Dudepro1237** [FireMario211/Prism-Menu#86]
### Platform

Android

### Version

1.6.2

### Describe the bug

Uploading az_recorder_20240420_133439_edited.mp4…

### Expected Behavior

This is how 

### How to reproduce

Djjdjf

### Mods Installed

Ndjfjx

### Crash Logs

Fhhfcjgb

### Additional Context

Hthgvj

**Comment by FireMario211** [comment]
not a valid video because it hasn't been uploaded.

Also next time, reply on the current issue instead of making a new one
