### ISSUE TITLE
Add to android version

### ISSUE THREAD

**Issue by QPLAYid** [FireMario211/Prism-Menu#90]
Can you add android version ?

**Comment by QPLAYid** [comment]
> add what

Btw you source only for pc right ?
Can add for android too ?

**Comment by QPLAYid** [comment]
> add what

Example android

https://github.com/AKNoryx28/zygisk-imgui-modmenu

**Comment by MegaSa1nt** [comment]
> Can you add android version ?

it is literally on android, download Geode and find "Prism Menu"

**Comment by FireMario211** [comment]
there is nothing to add, Prism Menu is already available for all platforms on Geode

goodbye

**Comment by QPLAYid** [comment]
> there is nothing to add, Prism Menu is already available for all platforms on Geode
> 
> goodbye

Only for geometri dash ?
