### ISSUE TITLE
Looking for some .gdr files.

### ISSUE THREAD

**Issue by DragosDobrican** [FireMario211/Prism-Menu#93]
i need to know, where is the **.gdr** files stored in the Geode Directory?

**Comment by FireMario211** [comment]
It's located in the GD Save Directory / geode / mods / firee.PrismMenu / macros


Or if you don't know where GD SAVE directory is
Win - `%localappdata%\GeometryDash\geode\mods\firee.PrismMenu\macros`
Android - `Geode / save / geode / mods / firee.PrismMenu / macros`
Mac - idk where GD Save dir is
