### ISSUE TITLE
[Bug]: GD Crashing 90% of the time

### ISSUE THREAD

**Issue by Dannybcnc** [FireMario211/Prism-Menu#96]
### Platform

Windows

### Version

latest version atm (5/12/2024: GMT+2 6 40 PM)

### Describe the bug

sometimes when i open gd it just crashes like 3 times in a row then it works
and yes i do have steam running in the bg

### Expected Behavior

not crash on me lmao

### How to reproduce

just open the game lmao,doesnt matter if its directly the .exe or from steam
i cant replicate it every single time but i got crash file thing 

### Mods Installed

![image](https://github.com/FireMario211/Prism-Menu/assets/95192812/db70d842-2c82-4727-b6e6-77f214afd21b)

### Crash Logs

[2024-05-10_17-46-08.log](https://github.com/FireMario211/Prism-Menu/files/15286902/2024-05-10_17-46-08.log)

**Comment by FireMario211** [comment]
Unrelated to Prism Menu, crash log is related to GD Mega Overlay
